create table public.login_logs (
  id bigint generated by default as identity primary key,
  email varchar not null,
  ip varchar not null,
  user_agent text,
  timestamp timestamptz not null default now(),
  success boolean not null
);

-- Enable Row Level Security (optional)
alter table public.login_logs enable row level security;

-- Grant public select/insert to anon role (adjust as needed)
grant select, insert on public.login_logs to anon;
